package com.wqzhang.thingswapper.dao.greendao;

import org.greenrobot.greendao.annotation.*;

import java.util.List;
import com.wqzhang.thingswapper.dao.greendao.DaoSession;
import org.greenrobot.greendao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "TO_DO_THING".
 */
@Entity(active = true)
public class ToDoThing {

    @Id
    private Long id;
    private String reminderContext;
    private Integer reminderType;
    private java.util.Date createDate;
    private java.util.Date finshDate;
    private Integer Status;
    private Boolean isSynchronize;
    private Long userId;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient ToDoThingDao myDao;

    @ToOne(joinProperty = "userId")
    private User user;

    @Generated
    private transient Long user__resolvedKey;

    @ToMany(joinProperties = {
        @JoinProperty(name = "id", referencedName = "toDoThingId")
    })
    private List<Connection_T_N> notificationIds;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public ToDoThing() {
    }

    public ToDoThing(Long id) {
        this.id = id;
    }

    @Generated
    public ToDoThing(Long id, String reminderContext, Integer reminderType, java.util.Date createDate, java.util.Date finshDate, Integer Status, Boolean isSynchronize, Long userId) {
        this.id = id;
        this.reminderContext = reminderContext;
        this.reminderType = reminderType;
        this.createDate = createDate;
        this.finshDate = finshDate;
        this.Status = Status;
        this.isSynchronize = isSynchronize;
        this.userId = userId;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getToDoThingDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getReminderContext() {
        return reminderContext;
    }

    public void setReminderContext(String reminderContext) {
        this.reminderContext = reminderContext;
    }

    public Integer getReminderType() {
        return reminderType;
    }

    public void setReminderType(Integer reminderType) {
        this.reminderType = reminderType;
    }

    public java.util.Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(java.util.Date createDate) {
        this.createDate = createDate;
    }

    public java.util.Date getFinshDate() {
        return finshDate;
    }

    public void setFinshDate(java.util.Date finshDate) {
        this.finshDate = finshDate;
    }

    public Integer getStatus() {
        return Status;
    }

    public void setStatus(Integer Status) {
        this.Status = Status;
    }

    public Boolean getIsSynchronize() {
        return isSynchronize;
    }

    public void setIsSynchronize(Boolean isSynchronize) {
        this.isSynchronize = isSynchronize;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /** To-one relationship, resolved on first access. */
    @Generated
    public User getUser() {
        Long __key = this.userId;
        if (user__resolvedKey == null || !user__resolvedKey.equals(__key)) {
            __throwIfDetached();
            UserDao targetDao = daoSession.getUserDao();
            User userNew = targetDao.load(__key);
            synchronized (this) {
                user = userNew;
            	user__resolvedKey = __key;
            }
        }
        return user;
    }

    @Generated
    public void setUser(User user) {
        synchronized (this) {
            this.user = user;
            userId = user == null ? null : user.getId();
            user__resolvedKey = userId;
        }
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<Connection_T_N> getNotificationIds() {
        if (notificationIds == null) {
            __throwIfDetached();
            Connection_T_NDao targetDao = daoSession.getConnection_T_NDao();
            List<Connection_T_N> notificationIdsNew = targetDao._queryToDoThing_NotificationIds(id);
            synchronized (this) {
                if(notificationIds == null) {
                    notificationIds = notificationIdsNew;
                }
            }
        }
        return notificationIds;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetNotificationIds() {
        notificationIds = null;
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
